module.exports = {
  components: {
    categories: [
      {
        name: "Components",
        include: [
          // "src/components/ResponsiveContainer/ResponsiveContainer.tsx",
          "src/components/slider/Slider.tsx",
          "src/components/SliderJS/SliderJS.jsx",
          "src/components/ArrayTest/ArrayTest.tsx",
          "src/components/BulletedList/BulletedList.tsx",
          "src/components/BulletedListItem/BulletedListItem.tsx",
          "src/components/Chip/Chip.tsx",
          "src/components/DateInput/DateInput.tsx",
          "src/components/Button/Button.tsx",
          "src/components/Select/Select.tsx",
          "src/components/Card/Card.tsx",
          "src/components/Accordion/Accordion.tsx",
          // "src/components/AccordionGroup/AccordionGroup.tsx",
          // "src/components/AccordionGroupItem/AccordionGroupItem.tsx",
          "src/components/Typography/Typography.tsx",
          "src/components/Dialog/Dialog.tsx",
          "src/components/Tabs/Tabs.tsx",
          "src/components/Icon/Icon.tsx",
          "src/components/Checkbox/Checkbox.tsx",
          "src/components/Heading/Heading.tsx",
          "src/components/TextInput/TextInput.tsx",
          "src/components/ToggleGroup/ToggleGroup.tsx",
          "src/components/Alert/Alert.tsx",
          "src/components/Dropdown/Dropdown.tsx",
          "src/components/QuickNav/QuickNav.tsx",
          "src/components/NavTabs/NavTabs.tsx",
          "src/components/NavTab/NavTab.tsx",
          "src/components/Wizard/Wizard.tsx",
          "src/components/Paginator/Paginator.tsx",
          "src/components/ResultsetTable/ResultsetTable.tsx",
          "src/components/Table/Table.tsx",
          "src/components/Table/TableHead/TableHead.tsx",
          "src/components/Table/TableHeader/TableHeader.tsx",
          "src/components/Table/TableBody/TableBody.tsx",
          "src/components/Table/TableRow/TableRow.tsx",
          "src/components/Table/TableCell/TableCell.tsx",
        ],
      },
      {
        name: "Containers",
        include: [
          "src/components/Flex/Flex.tsx",
          "src/components/Inset/Inset.tsx",
          "src/components/Bleed/Bleed.tsx",
          "src/components/Box/Box.tsx",
          "src/components/Grid/Grid.tsx",
          'src/components/Grid/GridItem/GridItem.tsx',
        ],
      },
      {
        name: "App Layout",
        include: [
          "src/components/ApplicationLayout/ApplicationLayout.tsx",
          "src/components/Header/Header.tsx",
          "src/components/Main/Main.tsx",
          "src/components/Footer/Footer.tsx",
          "src/components/Sidenav/Sidenav.tsx",
          "src/components/SidenavGroup/SidenavGroup.tsx",
          "src/components/SidenavLink/SidenavLink.tsx",
          "src/components/SidenavSection/SidenavSection.tsx",
          "src/components/SidenavTitle/SidenavTitle.tsx",
          "src/components/HeaderDropdown/HeaderDropdown.tsx",
        ],
      },
      {
        name: "Utilities",
        include: [
          "src/components/ThemeCustomizer/ThemeCustomizer.js",
        ],
      },
    ],
    wrapper: "src/components/UXPinWrapper/UXPinWrapper.js",
    webpackConfig: "webpack.config.js",
  },
  name: "DXC Halstack Design System",
};
